(() => {
  const board=document.querySelector('#drawingBoard'); const canvas=document.querySelector('#circleCanvas'); const ctx=canvas.getContext('2d'); const mark=document.querySelector('#startMark');
  let points=[]; let drawing=false;
  function resize(){const r=board.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0);redraw()}
  function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
  function redraw(){ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);if(points.length<2)return;ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let i=1;i<points.length;i++)ctx.lineTo(points[i].x,points[i].y);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=7;ctx.strokeStyle='#24a66a';ctx.stroke()}
  function start(e){if(board.classList.contains('scored'))return;e.preventDefault();drawing=true;points=[point(e)];board.classList.add('drawing');mark.style.left=`${points[0].x}px`;mark.style.top=`${points[0].y}px`;canvas.setPointerCapture(e.pointerId);redraw()}
  function move(e){if(!drawing)return;e.preventDefault();const p=point(e),last=points.at(-1);if(Math.hypot(p.x-last.x,p.y-last.y)>=2){points.push(p);redraw()}}
  function finish(e){if(!drawing)return;drawing=false;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);board.classList.remove('drawing');if(points.length<16){document.querySelector('#tip').textContent='轨迹太短啦，再画一个完整的圆';reset(false);return}show(analyze(points))}
  function analyze(raw){let length=0;for(let i=1;i<raw.length;i++)length+=Math.hypot(raw[i].x-raw[i-1].x,raw[i].y-raw[i-1].y);const cx=raw.reduce((s,p)=>s+p.x,0)/raw.length,cy=raw.reduce((s,p)=>s+p.y,0)/raw.length;const radii=raw.map(p=>Math.hypot(p.x-cx,p.y-cy)),mean=radii.reduce((a,b)=>a+b,0)/radii.length;const deviation=Math.sqrt(radii.reduce((s,r)=>s+(r-mean)**2,0)/radii.length)/Math.max(mean,1);const bins=new Set(raw.map(p=>Math.floor(((Math.atan2(p.y-cy,p.x-cx)+Math.PI)/(Math.PI*2))*72)%72));const coverage=Math.min(1,bins.size/68),gap=Math.hypot(raw[0].x-raw.at(-1).x,raw[0].y-raw.at(-1).y),closure=Math.max(0,1-gap/Math.max(mean*.72,1)),roundness=Math.max(0,Math.min(1,1-deviation/.28)),overdraw=Math.max(0,length/Math.max(Math.PI*2*mean,1)-1.18),size=Math.min(1,mean/48);const score=Math.round(100*Math.max(0,(roundness*.62+closure*.23+coverage*.15-overdraw*.28)*size));return{score:Math.min(100,score),roundness,closure,coverage}}
  function show(r){board.classList.add('scored');document.querySelector('#score').textContent=r.score;document.querySelector('#roundness').textContent=`${Math.round(r.roundness*100)}%`;document.querySelector('#closure').textContent=`${Math.round(r.closure*100)}%`;document.querySelector('#coverage').textContent=`${Math.round(r.coverage*100)}%`;document.querySelector('#verdict').textContent=r.score>=96?'圆规本人':r.score>=90?'这圆相当漂亮':r.score>=80?'很接近完美了':r.score>=65?'有点圆，再稳一点':'它有自己的想法';document.querySelector('#tip').textContent='松手即评分，看看你能不能破纪录';const best=Math.max(r.score,Number(localStorage.getItem('perfectCircleBest')||0));localStorage.setItem('perfectCircleBest',best);document.querySelector('#bestScore').textContent=best}
  function reset(tip=true){points=[];drawing=false;board.classList.remove('drawing','scored');if(tip)document.querySelector('#tip').textContent='按住屏幕，一笔画出你心里的圆';redraw()}
  board.addEventListener('pointerdown',start);board.addEventListener('pointermove',move);board.addEventListener('pointerup',finish);board.addEventListener('pointercancel',finish);document.querySelector('#retryButton').addEventListener('click',()=>reset());document.querySelector('#bestScore').textContent=localStorage.getItem('perfectCircleBest')||'--';window.addEventListener('resize',resize);resize();
})();
